name: .NET Build Por Hora

on: 
  push: 
    branches:
      - main

  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar pacotes
        run: dotnet restore github4women/github4women.csproj

      - name: Compilar o projeto
        run: dotnet build github4women/github4women.csproj --configuration Release

      - name: Rodar testes
        run: dotnet test github4women/github4women.csproj --no-build --verbosity normal || echo "Sem testes definidos"
