name: .NET Build Por Hora

on: 
  push: 
    branches:
      - main

  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Action oficial do GitHub para fazer o checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # Action pré-existente para configurar o .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # ou a versão do seu projeto

      # Script personalizado para restaurar pacotes
      - name: Restaurar pacotes
        run: dotnet restore

      # Script personalizado para compilar o projeto
      - name: Compilar o projeto
        run: dotnet build --configuration Release

      # Script personalizado para rodar testes (caso existam)
      - name: Rodar testes
        run: dotnet test
